# Generated by Django 3.0.5 on 2020-11-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201108_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='stock',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('Elecronics', 'Elecronics'), ('IT Equipment', 'IT Equipment'), ('Phone', 'Phone')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
